### ISSUE TITLE
DB bug

### ISSUE THREAD

**Issue by romaissaghdjt** [edityomurti/Hotel-Reservation-Netbeans-MySQL#1]
hi mr ... thank you for this app ... can you send me the passeword...  because i cant contact to the data base ...

**Comment by edityomurti** [comment]
@romaissaghdjt 
Unfortunately, the database I stored online is now unavailable. 
In addition to this issue, please import this attached sql file then you need to apply it in [Koneksi.java](https://github.com/edityomurti/Hotel-Reservation-Netbeans-MySQL/blob/master/src/koneksi/Koneksi.java) on line 32.

[hotel_damai.sql.zip](https://github.com/edityomurti/Hotel-Reservation-Netbeans-MySQL/files/1702629/hotel_damai.sql.zip)

**Comment by romaissaghdjt** [comment]
thank you mr ^^ ... i don t know how i can connecte the data base ... can you helpe me to send photo to the line .. please

**Comment by edityomurti** [comment]
@romaissaghdjt 
Please try to change the db connection configuration that suits to your own db in [Koneksi.java](https://github.com/edityomurti/Hotel-Reservation-Netbeans-MySQL/blob/master/src/koneksi/Koneksi.java) on line 32.

![Koneksi.java](https://user-images.githubusercontent.com/14180222/37888854-c1a0e2d4-30f3-11e8-9b15-26370cf8c5fd.png)

**Comment by romaissaghdjt** [comment]
ah okey ... Thank you for correcting it .... Thank you for this application ... It has helped me a lot ^^

**Comment by romaissaghdjt** [comment]
I wish you more success
